"use client";
import Link from "next/link";
import NavigationHeader from "./NavigationHeader";
import { useState } from "react";
import { startHref, startLabel } from "../../lib/customer-flow";
export default function Contact({ available }: { available: boolean }) {
  const [busy, setBusy] = useState(false), [sent, setSent] = useState(false), [error, setError] = useState("");
  return <main className="mk-site contact-site"><NavigationHeader/><section className="mk-container contact-grid"><div><span className="mk-kicker">A considered beginning</span><h1>Your business.<br/><em>Your questions.</em></h1><p>Tell us what you have in mind. A useful starting point is what you offer, who you want to reach and what your website needs to help them do.</p><p>Before any paid work begins, we agree the pages, content responsibilities, timing, ongoing costs and handover. Those details belong in your project agreement.</p><Link className="mk-button mk-button-outline" href={startHref()}>{startLabel} ↗</Link></div><div className="contact-panel">{available ? sent ? <div role="status"><span className="mk-kicker">Enquiry received</span><h2>We have your<br/><em>starting point.</em></h2><p>Your message has been accepted by our email service. Keep a copy of your project details for the next conversation.</p><Link href="/work">Explore the work ↗</Link></div> : <form onSubmit={async event => { event.preventDefault(); if (busy) return; setBusy(true); setError(""); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), email: form.get("email"), message: form.get("message"), website: form.get("website"), key: crypto.randomUUID() }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Your message could not be sent. Try again."); setSent(true); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }}><h2>Ask about your project.</h2><label>Your name<input name="name" autoComplete="name" required maxLength={100}/></label><label>Email<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><label>What would you like to discuss?<textarea name="message" rows={7} required minLength={10} maxLength={3000}/></label><label className="contact-trap" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><p className="contact-note">We use these details to respond to your enquiry. Sending a message does not create an account or begin paid work.</p>{error && <p role="alert">{error} Your message remains in the form.</p>}<button className="mk-button mk-button-dark" type="submit" disabled={busy}>{busy ? "Sending enquiry…" : "Send enquiry ↗"}</button></form> : <div><span className="mk-kicker">Explore before committing</span><h2>Find your<br/><em>starting point.</em></h2><p>Online enquiries are not available yet. You can explore the portfolio, try the portal and write and download your own website brief.</p><p>Your brief can be saved without an account or payment.</p><Link className="mk-button mk-button-dark" href={startHref()}>{startLabel} ↗</Link><Link className="contact-secondary" href="/work">Explore 20 website concepts ↗</Link></div>}</div></section></main>;
}
