"use client";
import Link from "next/link";
import NavigationHeader from "./NavigationHeader";
import { useState } from "react";
import { startHref, startLabel } from "../../lib/customer-flow";
export default function Contact({ available }: { available: boolean }) {
  const [busy, setBusy] = useState(false), [sent, setSent] = useState(false), [error, setError] = useState("");
  return <main className="mk-site contact-site"><NavigationHeader/><section className="mk-container contact-grid"><div><span className="mk-kicker">Your website project</span><h1>Your business.<br/><em>Your questions.</em></h1><p>Tell us what you offer, who you want to reach and what visitors should be able to do on your website.</p><p>Before paid work begins, we agree the pages, features, content, timing, costs and handover in your project agreement.</p><Link className="mk-button mk-button-outline" href={startHref()}>{startLabel} ↗</Link></div><div className="contact-panel">{available ? sent ? <div role="status"><span className="mk-kicker">Enquiry received</span><h2>Your enquiry<br/><em>is submitted.</em></h2><p>Your enquiry was submitted successfully. Keep a copy of your project details for your records.</p><Link href="/work">Explore the work ↗</Link></div> : <form onSubmit={async event => { event.preventDefault(); if (busy) return; setBusy(true); setError(""); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), email: form.get("email"), message: form.get("message"), website: form.get("website"), key: crypto.randomUUID() }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Your message could not be sent. Try again."); setSent(true); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }}><h2>Ask about your project.</h2><label>Your name<input name="name" autoComplete="name" required maxLength={100}/></label><label>Email<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><label>What would you like to discuss?<textarea name="message" rows={7} required minLength={10} maxLength={3000}/></label><label className="contact-trap" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><p className="contact-note">We use these details to respond to your enquiry. Sending an enquiry does not create an account or commit you to paid work.</p>{error && <p role="alert">{error} Your message remains in the form.</p>}<button className="mk-button mk-button-dark" type="submit" disabled={busy}>{busy ? "Sending enquiry…" : "Send enquiry ↗"}</button></form> : <div><span className="mk-kicker">Prepare your brief</span><h2>Put your ideas<br/><em>in writing.</em></h2><p>Online enquiry sending is not available yet. You can still write a website brief, save it on this device or download a copy.</p><p>You can start with a few notes. No account or payment is needed.</p><Link className="mk-button mk-button-dark" href={startHref()}>{startLabel} ↗</Link><Link className="contact-secondary" href="/work">Explore the portfolio ↗</Link></div>}</div></section></main>;
}
