"use client";
import {useRef} from "react";
import Link from "next/link";
import {usePageMotion} from "../../lib/use-page-motion";
import NavigationHeader from "./NavigationHeader";
import ServiceFooter from "./ServiceFooter";
export default function HowWeWork(){
 const root=useRef<HTMLElement>(null);usePageMotion(root);
 return <main ref={root} className="mk-site mk-simple mk-section-site" id="top"><a className="skip-link" href="#main-content">Skip to content</a><NavigationHeader/><div id="main-content" tabIndex={-1}>
 <header className="ff-section-intro mk-container"><span className="mk-kicker">How we work with you</span><h1 className="mk-display">Good work.<br/><span className="ff-accent-text">Clear collaboration.</span></h1><p>We handle the design and build. You see the progress, review the working website and keep your feedback in one place.</p></header>
 <section className="mk-process" id="process"><div className="mk-container"><div className="mk-process-rail">{[["01","Start with your business","Tell us what you do, who you serve and what visitors should do. We agree the pages, content and timing before work begins."],["02","See the design take shape","We design and build around your business. Follow progress and explore the working website in your client portal."],["03","Review, then refine","Submit your changes together as a revision round. Custom websites include three rounds; the one-page package includes one."],["04","Launch with confidence","Approve the website, complete the launch checks and connect your domain. After launch, update everyday words and images in your portal."]].map(([n,title,copy])=><div className="mk-process-step" data-reveal key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></div></section><section className="mk-portal" id="portal"><div className="mk-container mk-portal-summary"><div data-reveal><span className="mk-kicker">Your client portal</span><h2 className="mk-display">One place for<br/><em>your website.</em></h2><p className="mk-body">Review the working website, leave feedback beside the page and update words and images after launch.</p><Link className="mk-button mk-button-dark" href="/preview">Explore the client portal ↗</Link><p className="mk-preview-note">Try an example project. Edits stay on this device. No account or payment needed.</p></div><Link className="mk-portal-showcase" href="/preview?space=content&view=pages" aria-label="Try editing website content in the portal" data-reveal><img src="/portal-content-showcase.jpg" width="1363" height="936" alt="Fourthform client portal showing website content fields beside a live page preview" loading="lazy"/><span>Update your content. Keep your design. <span aria-hidden="true">↗</span></span></Link></div></section></div><ServiceFooter/></main>;
}
