"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {startHref,connectedPortal,startLabel,clientSignInHref} from "../../lib/customer-flow";
import FeaturedWork from "../work/FeaturedWork";
import PortfolioOrbit from "./PortfolioOrbit";
import {usePageMotion} from "../../lib/use-page-motion";

export default function MarketingHome(){
  const root=useRef<HTMLElement>(null),menuButton=useRef<HTMLButtonElement>(null),mobileMenu=useRef<HTMLDivElement>(null);
  const [menuOpen,setMenuOpen]=useState(false);
  usePageMotion(root);
  useEffect(()=>{if(!menuOpen)return;mobileMenu.current?.querySelector<HTMLAnchorElement>("a")?.focus();const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){setMenuOpen(false);menuButton.current?.focus();}};const outside=(event:PointerEvent)=>{if(!mobileMenu.current?.contains(event.target as Node)&&!menuButton.current?.contains(event.target as Node))setMenuOpen(false);};const query=matchMedia("(min-width:761px)"),resize=()=>{if(query.matches)setMenuOpen(false);};document.addEventListener("keydown",close);document.addEventListener("pointerdown",outside);query.addEventListener("change",resize);return()=>{document.removeEventListener("keydown",close);document.removeEventListener("pointerdown",outside);query.removeEventListener("change",resize);};},[menuOpen]);
  return <main ref={root} className="mk-site mk-simple mk-orbit-site" id="top">
    <a className="skip-link" href="#main-content">Skip to content</a>
    <nav className="mk-nav" aria-label="Primary navigation"><a className="mk-wordmark" href="#top"><span className="ff-mark" aria-hidden="true"/>fourthform</a><div className="mk-nav-links"><Link href="/work">Work</Link><a href="#process">How it works</a><a href="#pricing">Pricing</a></div><button ref={menuButton} className="mk-menu-toggle" type="button" aria-controls="mk-mobile-menu" aria-expanded={menuOpen} aria-label={menuOpen?"Close navigation":"Open navigation"} onClick={()=>setMenuOpen(open=>!open)}>{menuOpen?"Close":"Menu"}</button><a className="mk-button mk-button-dark" href={startHref()}>{startLabel}</a><div ref={mobileMenu} className="mk-mobile-menu" id="mk-mobile-menu" hidden={!menuOpen} onBlur={event=>{if(event.relatedTarget&&!event.currentTarget.contains(event.relatedTarget)&&event.relatedTarget!==menuButton.current)setMenuOpen(false);}}>{[["/work","Work"],["#process","How it works"],["#pricing","Pricing"],["/preview","Try the portal"],[clientSignInHref,"Client sign-in ↗"]].map(([href,label])=><a key={href} href={href} onClick={()=>{setMenuOpen(false);menuButton.current?.focus();}}>{label}</a>)}</div></nav>
    <section className="mk-hero-wrap" id="main-content" tabIndex={-1} aria-labelledby="hero-heading"><div className="mk-hero mk-orbit-hero"><PortfolioOrbit/><div className="mk-hero-copy mk-orbit-copy"><p className="mk-kicker mk-hero-eyebrow" data-intro>Custom websites for independent businesses</p><h1 className="mk-display" id="hero-heading" data-intro>A website.<span>All your own.</span></h1><p className="mk-body" data-intro>We design and build a custom website that makes your business clear, memorable and easy to choose.</p><div className="mk-hero-actions" data-intro><Link className="mk-button mk-button-dark" href="/work">See the work ↗</Link><a className="mk-text-link" href={startHref()}>{startLabel} ↗</a></div><p className="mk-included" data-intro>A$1,500 · Up to 5 pages · 3 revision rounds</p></div></div></section>
    <FeaturedWork/>
    <section className="mk-process" id="process"><div className="mk-container"><div className="mk-section-head" data-reveal><span className="mk-kicker">How it works</span><h2 className="mk-display">Your business.<br/><em>Our craft.</em></h2></div><div className="mk-process-rail">{[["01","Tell us what matters","Share your business, goals and references in a short brief."],["02","We design and build","We create your website. You can follow the progress in your client portal."],["03","Make it yours","Review the working website and collect your feedback. Three revision rounds are included."],["04","Launch and keep it current","Approve the result, connect your domain and launch. Update everyday content in your portal."]].map(([n,title,copy])=><div className="mk-process-step" data-reveal key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></div></section>
    <section className="mk-portal" id="portal"><div className="mk-container mk-portal-summary"><div data-reveal><span className="mk-kicker">The client portal</span><h2 className="mk-display">One place for<br/><em>your website.</em></h2><p className="mk-body">Leave feedback on the design, keep track of the project and update your website after launch. Everything is in one place.</p><Link className="mk-button mk-button-dark" href="/preview">Try the portal ↗</Link><p className="mk-preview-note">An interactive example. No account or payment needed.</p></div><Link className="mk-portal-showcase" href="/preview?space=content&view=pages" aria-label="Try editing website content in the portal" data-reveal><img src="/portal-content-showcase.jpg" width="1363" height="936" alt="Fourthform client portal showing website content fields beside a live page preview" loading="lazy"/><span>Edit content. Keep the design. <span aria-hidden="true">↗</span></span></Link></div></section>
    <section className="mk-pricing" id="pricing"><div className="mk-container"><div className="mk-pricing-head" data-reveal><div><span className="mk-kicker">The website package</span><h2 className="mk-display">Built around you.</h2></div><p className="mk-body">A$200 to start. A$1,300 when you approve the website for launch.</p></div><div className="mk-price-line" data-reveal><span>Fourthform Site</span><strong>A$1,500 <small>once</small></strong><div><ul className="mk-scope-list"><li>Up to 5 custom pages, designed and built for your business</li><li>Responsive design, enquiry forms, search setup and analytics</li><li>3 revision rounds</li><li>Client portal and everyday content updates included</li></ul><a className="mk-button mk-button-dark mk-price-action" href={startHref()}>{startLabel} ↗</a></div></div><p className="mk-pricing-note">Prices in Australian dollars. Domain registration is separate. Extra revision rounds are A$150.</p><details className="mk-package-details"><summary>Smaller website or extra tools?<span aria-hidden="true">+</span></summary><div><div className="mk-first"><span>Fourthform First</span><p>For businesses opened within the last six months. One page with around 6 to 7 sections and one revision round. Everyday content tools included. <a className="mk-text-link" href={startHref({package:"first"})}>Explore First ↗</a></p><strong>A$199</strong></div><div className="mk-price-secondary"><div><span>Core</span><strong>Included</strong><p>Content updates, basic analytics, search details and domain management.</p></div><div><span>Pro</span><strong>A$39 / month</strong><p>Optional tools: scheduled States, deeper analytics and search insights. <Link href="/preview?space=content&view=states">Explore the example ↗</Link></p></div></div></div></details></div></section>
    <section className="mk-faq" id="questions"><div className="mk-container mk-faq-grid"><div data-reveal><span className="mk-kicker">Before you begin</span><h2 className="mk-display">A few useful<br/><em>answers.</em></h2></div><div className="mk-faq-list"><details><summary>What should I have ready?<span aria-hidden="true">+</span></summary><p>A description of your business, the people you want to reach and what the website should help them do. Bring any words, images or design references you already have. We agree the page list, features, content responsibilities and timing before the build.</p></details><details><summary>How do the revisions work?<span aria-hidden="true">+</span></summary><p>Review the working website and collect all the changes you want. Submit them together as one revision round. The Site package includes three rounds. Saving feedback drafts and sharing your initial brief use no round.</p></details><details><summary>Can I change the website after launch?<span aria-hidden="true">+</span></summary><p>Yes. Your included Core tools let you update everyday content, check basic analytics and manage search details and your domain. Larger design changes need a separate scope.</p></details><details><summary>What about shops, booking systems or custom features?<span aria-hidden="true">+</span></summary><p>They need a separate scope. <Link href="/contact">Tell us what you need</Link> so we can agree the features, costs, hosting, ownership and support before you begin.</p></details></div></div></section>
    <section className="mk-final"><div className="mk-container mk-final-grid" data-reveal><h2 className="mk-display">Let’s give your business<br/><em>its own form.</em></h2><div><p className="mk-body">Tell us what you have in mind.</p><a className="mk-button mk-button-dark" href={startHref()}>{startLabel} ↗</a><p className="mk-start-note">{connectedPortal?"Save your brief and start when you are ready.":"Try the brief. No account or payment needed."}</p></div></div></section>
    <footer className="mk-footer"><div className="mk-container"><b>fourthform</b><span>Custom websites. Brisbane, Australia.</span><div className="mk-footer-links"><Link href="/contact">Contact</Link><Link href="/preview">Portal preview</Link><a href={clientSignInHref}>Client sign-in ↗</a></div></div></footer>
  </main>;
}
