import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
const base=process.env.PREVIEW_URL||'http://127.0.0.1:3000',portal=`${base}/portal-preview/index.html`;
const browser=await chromium.launch({args:['--no-sandbox']}),results=[],errors=[];
await mkdir('docs/preview-evidence',{recursive:true});
async function check(name,fn,options={}){const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce',...options}),page=await context.newPage();page.setDefaultTimeout(8000);page.on('pageerror',error=>errors.push({name,error:error.message}));try{await fn(page);results.push({name,result:'pass'});}catch(error){results.push({name,result:'fail',detail:error.message});await page.screenshot({path:`docs/preview-evidence/release-failure-${results.length}.png`}).catch(()=>{});}finally{await context.close();}}
await check('Fourthform fonts load locally across the homepage and focused portal',async page=>{await page.goto(base);await page.evaluate(()=>document.fonts.ready);assert.match(await page.locator('.mk-hero h1').evaluate(e=>getComputedStyle(e).fontFamily),/Schibsted Grotesk/);assert.ok(await page.evaluate(()=>Array.from(document.fonts).some(f=>f.family.includes('Schibsted Grotesk')&&f.status==='loaded')));assert.equal((await page.request.get(`${base}/fonts/schibsted-grotesk.woff2`)).status(),200);assert.ok(await page.evaluate(()=>Array.from(document.fonts).some(f=>f.family.includes('Schibsted Grotesk')&&f.status==='loaded')));assert.equal((await page.request.get(`${base}/fonts/schibsted-grotesk.woff2`)).status(),200);await page.goto(`${portal}?space=content&view=pages`);await page.evaluate(()=>document.fonts.ready);assert.match(await page.locator('[data-view-panel="pages"] .ops-title').evaluate(e=>getComputedStyle(e).fontFamily),/Schibsted Grotesk/);assert.ok(await page.evaluate(()=>Array.from(document.fonts).some(f=>f.family.includes('Schibsted Grotesk')&&f.status==='loaded')));});
await check('The editable example brief opens without asking for credentials',async page=>{await page.goto(`${base}/preview/start`);await page.locator('[name="businessName"]').waitFor();assert.equal(await page.locator('[name="businessName"]').inputValue(),'Mori House');assert.equal(await page.locator('[name="password"]:visible').count(),0);await page.getByRole('button',{name:'Save & continue'}).click();assert.match(await page.locator('.obp-summary').textContent(),/A\$200/);});
await check('Portfolio filters, browser Back and phone panes preserve exploration',async page=>{await page.goto(`${base}/work`);await page.getByLabel('Business type').selectOption('Architecture');assert.ok(await page.locator('.portfolio-card').count()>0);assert.match(page.url(),/sector=Architecture/);await page.locator('.portfolio-card button').first().click();await page.locator('.work-dialog[open]').waitFor();await page.goBack();await page.locator('.work-dialog[open]').waitFor({state:'hidden'});assert.equal(await page.getByLabel('Business type').inputValue(),'Architecture');await page.locator('.portfolio-card button').first().click();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Show original image',exact:true}).click();await page.locator('.work-dialog-media img').evaluate(image=>image.decode());assert.ok(await page.locator('.work-dialog-media img').isVisible());await page.screenshot({path:'docs/preview-evidence/release-portfolio-phone-website.png'});await page.getByRole('button',{name:'About this design'}).click();assert.ok(await page.locator('#work-dialog-description').isVisible());assert.equal(await page.locator('.work-dialog-media img').isVisible(),false);await page.screenshot({path:'docs/preview-evidence/release-portfolio-phone-about.png'});});
await check('Embedded phone preview removes duplicate navigation and keeps its content usable',async page=>{await page.goto(`${portal}?space=content&view=pages&embed=1`);assert.equal(await page.locator('.top').isVisible(),false);assert.equal(await page.locator('#leftRail').isVisible(),false);assert.ok(await page.locator('[data-field="heading"]').isVisible());const widths=await page.locator('.center').evaluate(e=>({width:e.clientWidth,viewport:innerWidth}));assert.ok(Math.abs(widths.width-widths.viewport)<=1);await page.screenshot({path:'docs/preview-evidence/release-embedded-phone.png'});},{viewport:{width:320,height:780}});
await check('First carries its price, round limit and single-page example into the portal',async page=>{await page.goto(`${base}/preview/start?package=first`);await page.getByRole('button',{name:'Save & continue'}).click();await page.getByRole('button',{name:'Explore example checkout'}).click();await page.getByRole('link',{name:'Open Initial Direction'}).click();await page.waitForURL('**/portal-preview/index.html?**');await page.waitForFunction(()=>window.ffPreviewPackage&&typeof window.showView==='function');assert.equal(await page.evaluate(()=>window.ffPreviewPackage.rounds),1);await page.evaluate(()=>showView('billing'));const billing=await page.locator('[data-view-panel="billing"]').textContent();assert.match(billing,/A\$199/);assert.ok(!billing.includes('A$1,300'));await page.evaluate(()=>showView('review'));assert.equal(await page.locator('.canvasbar [data-page="Menu"]').isVisible(),false);});
await check('Saving CMS keeps a draft until the explicit publication confirmation',async page=>{await page.goto(`${portal}?view=pages`);await page.locator('[data-field="heading"]').fill('A locally published example heading');await page.locator('[data-ops="draft-cms"]').click();await page.evaluate(()=>showView('review'));assert.notEqual(await page.locator('#moriPage h1').textContent(),'A locally published example heading');await page.evaluate(()=>showView('pages'));await page.locator('[data-ops="review-cms"]').click();assert.match(await page.locator('#opsModal').textContent(),/Changed fields:.*heading/);await page.locator('[data-ops="save-cms"]').click();await page.evaluate(()=>showView('review'));assert.equal(await page.locator('#moriPage h1').textContent(),'A locally published example heading');});
await check('State activation retains an independent snapshot when its draft changes',async page=>{await page.goto(`${portal}?space=content&view=states`);await page.locator('[data-field="stateHeading"]').fill('Activated evening heading');await page.locator('[data-ops="save-state"]').click();assert.equal(await page.evaluate(()=>ffLocalSnapshot().operations.activatedState),null);await page.locator('[data-ops="activate-state"]').click();await page.locator('[data-ops="confirm-state"]').click();assert.equal(await page.evaluate(()=>ffLocalSnapshot().operations.activatedState.stateHeading),'Activated evening heading');await page.locator('[data-field="stateHeading"]').fill('New unfinished draft');await page.locator('[data-ops="save-state"]').click();assert.equal(await page.evaluate(()=>ffLocalSnapshot().operations.activatedState.stateHeading),'Activated evening heading');await page.reload();assert.equal(await page.evaluate(()=>ffLocalSnapshot().operations.activatedState.stateHeading),'Activated evening heading');});
await check('Revision submission works with a single keyboard activation after acknowledgement',async page=>{await page.goto(portal);await page.locator('#submitBtn').click();assert.ok(await page.locator('#revisionConfirm').isDisabled());await page.locator('#revisionAcknowledge').check();await page.locator('#revisionConfirm').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>ffCommunicationFields().revisionUsed),1);assert.ok(await page.locator('#submitBtn').isDisabled());});
await check('Unavailable agency enquiries disclose the boundary before any submission',async page=>{await page.goto(`${base}/contact`);assert.match(await page.locator('main').textContent(),/Online enquiry sending is not available yet/);const response=await page.request.post(`${base}/api/contact`,{data:{name:'Example visitor',email:'example@example.test',message:'Example enquiry only'}});assert.equal(response.status(),503);});
await check('Accessible daily sample counts match the selected report total',async page=>{await page.goto(`${portal}?view=analytics`);for(const range of ['0','1','2']){await page.locator(`[data-range="${range}"]`).click();const total=Number((await page.locator('[data-metric]').first().textContent()).replaceAll(',',''));const sum=await page.locator('[data-daily-rows]').evaluate(e=>[...e.querySelectorAll('tr')].reduce((n,row)=>n+Number(row.lastElementChild.textContent),0));assert.equal(sum,total);}});
await check('Automatic desktop motion leaves essential pricing and content visible',async page=>{await page.goto(base);await page.waitForFunction(()=>document.querySelector('.mk-site').classList.contains('mk-motion'));await page.goto(base+'/pricing');await page.waitForTimeout(1000);assert.equal(await page.locator('.mk-price-line').evaluate(e=>getComputedStyle(e).clipPath),'none');await page.screenshot({path:'docs/preview-evidence/release-pricing-desktop.png'});await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.querySelector('.mk-site').classList.contains('mk-motion'));await page.goto(base);await page.screenshot({path:'docs/preview-evidence/release-marketing-desktop.png'});},{reducedMotion:'no-preference'});
await writeFile('docs/preview-evidence/release-results.json',JSON.stringify({results,uncaughtErrors:errors},null,2));console.log(JSON.stringify({results,uncaughtErrors:errors},null,2));await browser.close();if(results.some(r=>r.result==='fail')||errors.length)process.exitCode=1;
