"use client";
import { useState } from "react";
import { defaultSite, manifestSchema, contentSchema } from "../lib/site/schema";
import { validateContent, type ContentField } from "../lib/site/service";
import { api } from "../lib/client";
import type { Project } from "../lib/model";
import Dialog from "./Dialog";
export default function SiteSetup({ project }: { project: Project }) {
  const [site,setSite]=useState(()=>defaultSite(project)), [advanced,setAdvanced]=useState(""), [busy,setBusy]=useState(false), [confirm,setConfirm]=useState(false), [status,setStatus]=useState(""), [error,setError]=useState("");
  function field(pageId:string,fieldId:string,patch:Partial<ContentField>) { setSite(s=>({...s,manifest:{...s.manifest,pages:s.manifest.pages.map(p=>p.id===pageId?{...p,fields:p.fields.map(f=>f.id===fieldId?{...f,...patch}:f)}:p)}}));setError(""); }
  function review() { try { manifestSchema.parse(site.manifest);contentSchema.parse(site.content);const issues=validateContent(site.manifest,site.content);if(issues.length)throw new Error(issues.join("\n"));setError("");setConfirm(true); } catch(e) {setError((e as Error).message);} }
  return <details className="connected-card agency-site-setup"><summary>Agency website setup</summary><p>Define the pages, visual direction and editable fields before delivering review. Field IDs stay stable so Directions keep their targets. An existing website cannot be replaced here.</p><fieldset disabled={busy}><legend>Visual direction</legend><label>Business name<input value={site.manifest.theme?.name||""} maxLength={160} onChange={e=>setSite(s=>({...s,manifest:{...s.manifest,theme:{...s.manifest.theme!,name:e.target.value}}}))}/></label><label>Layout<select value={site.manifest.theme?.layout||"editorial"} onChange={e=>setSite(s=>({...s,manifest:{...s.manifest,theme:{...s.manifest.theme!,layout:e.target.value as "editorial"}}}))}>{["editorial","immersive","product","expressive"].map(layout=><option key={layout}>{layout}</option>)}</select></label><div className="connected-actions">{(["background","ink","accent"] as const).map(key=><label key={key}>{key}<input type="color" value={site.manifest.theme?.[key]||"#191a18"} onChange={e=>setSite(s=>({...s,manifest:{...s.manifest,theme:{...s.manifest.theme!,[key]:e.target.value}}}))}/></label>)}</div></fieldset>
  {site.manifest.pages.map(page=><fieldset key={page.id} disabled={busy}><legend>{page.title||"Untitled page"} · {page.id}</legend><label>Page title<input value={page.title} maxLength={160} onChange={e=>setSite(s=>({...s,manifest:{...s.manifest,pages:s.manifest.pages.map(p=>p.id===page.id?{...p,title:e.target.value}:p)}}))}/></label><label>Page path<input value={page.path} placeholder="/about" onChange={e=>setSite(s=>({...s,manifest:{...s.manifest,pages:s.manifest.pages.map(p=>p.id===page.id?{...p,path:e.target.value}:p)}}))}/></label>
  {page.fields.map(f=><details key={f.id} className="agency-field"><summary>{f.label} · {f.kind}</summary><p className="connected-code">Stable target: {f.id}</p><label>Field label<input value={f.label} onChange={e=>field(page.id,f.id,{label:e.target.value})}/></label><label>Presentation role<select value={f.role||""} onChange={e=>field(page.id,f.id,{role:(e.target.value||undefined) as ContentField["role"]})}><option value="">Additional section</option>{["heading","body","action-label","action-link","image","image-alt","image-focal-x","image-focal-y"].map(role=><option key={role}>{role}</option>)}</select></label>{f.kind!=="image"&&<><label>Starting content<textarea rows={3} maxLength={f.maxLength||10000} value={site.content.fields[f.id]||""} onChange={e=>setSite(s=>({...s,content:{...s.content,fields:{...s.content.fields,[f.id]:e.target.value}}}))}/></label><label>Character limit<input type="number" min={1} max={10000} value={f.maxLength||10000} onChange={e=>field(page.id,f.id,{maxLength:Number(e.target.value)})}/></label></>}{f.kind==="image"&&<><p>Upload the customer’s image in Pages after connection. Pair an image description field for meaningful images.</p><label className="check-label"><input type="checkbox" checked={!!f.decorative} onChange={e=>field(page.id,f.id,{decorative:e.target.checked})}/>Decorative image</label><label>Image description field<select value={f.altField||""} onChange={e=>field(page.id,f.id,{altField:e.target.value||undefined})}><option value="">Use page image description</option>{page.fields.filter(item=>item.kind==="text").map(item=><option value={item.id} key={item.id}>{item.label}</option>)}</select></label></>}</details>)}
  <div className="connected-actions">{(["text","link","image"] as const).map(kind=><button type="button" key={kind} onClick={()=>{const id=`field-${crypto.randomUUID()}`;setSite(s=>({...s,manifest:{...s.manifest,pages:s.manifest.pages.map(p=>p.id===page.id?{...p,fields:[...p.fields,{id,kind,label:`New ${kind}`,maxLength:kind==="text"?3000:undefined}]}:p)},content:{...s.content,fields:{...s.content.fields,[id]:""}}}));}}>Add {kind} field</button>)}</div></fieldset>)}
  <button disabled={busy||site.manifest.pages.length>=(project.package==="FIRST"?1:5)} onClick={()=>{const id=`page-${site.manifest.pages.length+1}`;setSite(s=>({...s,manifest:{...s.manifest,pages:[...s.manifest.pages,{id,path:`/${id}`,title:"New page",fields:[{id:`${id}-body`,kind:"text",label:"Introduction",role:"body",maxLength:3000}]}]},content:{...s.content,fields:{...s.content.fields,[`${id}-body`]:""},seo:{...s.content.seo,[id]:{title:"New page",description:"",noindex:false}}}}));}}>Add page</button>
  <details><summary>Advanced website definition</summary><p>Import a validated definition. Applying it replaces the local setup draft.</p><textarea rows={12} value={advanced} spellCheck={false} disabled={busy} onChange={e=>setAdvanced(e.target.value)} aria-label="Advanced JSON definition"/><button disabled={busy||!advanced} onClick={()=>{try{const value=JSON.parse(advanced);setSite({manifest:manifestSchema.parse(value.manifest),content:contentSchema.parse(value.content)});setAdvanced("");setError("");}catch(e){setError((e as Error).message);}}}>Apply definition to draft</button></details>
  <button className="primary" disabled={busy} onClick={review}>Review website setup</button>{error&&<p role="alert">{error}</p>}{status&&<p role="status">{status}</p>}{confirm&&<Dialog title="Connect this website definition?" onClose={()=>setConfirm(false)}><p>{project.name} · {site.manifest.pages.length} pages · {site.manifest.pages.reduce((n,p)=>n+p.fields.length,0)} editable fields.</p><ul>{site.manifest.pages.map(page=><li key={page.id}>{page.title} · {page.path}</li>)}</ul><p>This creates the website’s initial structure and review targets. It does not publish the site or send the client a message.</p><button disabled={busy} onClick={()=>setConfirm(false)}>Keep editing</button><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);setError("");try{const result=await api(`/api/projects/${project.id}/setup`,site);setStatus(`Website connected. Review URL: ${result.previewUrl}`);setConfirm(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?"Connecting website…":"Connect website"}</button>{error&&<p role="alert">{error}</p>}</Dialog>}</details>;
}
